on:
  repository_dispatch:
    types: [deploy-public-private]

jobs:
  show-client-payload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Show client payload
        run: |
          echo "Client payload: ${{ toJson(github.event.client_payload) }}"

      - name: service
        if: github.event.client_payload.service == 'hosting-research'
        run: |
          echo "Service is hosting-research"
          echo "Client payload: ${{ toJson(github.event.client_payload) }}"
